### ISSUE TITLE
Annotations are broken

### ISSUE THREAD

**Issue by felixsanz** [pyrochlore/obsidian-tracker#72]
Having this code:

``` tracker
searchType: task.done
searchTarget: Walk, Run
datasetName: Walk, Run
folder: Diary
month:
    mode: annotation
    annotation: 🚶‍♀️,🏃‍♀️
    startWeekOn: 'Mon'
    todayRingColor: orange
    selectedRingColor: white
    showSelectedValue: false
    todayRingColor: white
```

It outputs this.

![1631664728](https://user-images.githubusercontent.com/6182099/133350157-565070b4-6984-41b2-800a-579b05993fc1.png)

if i hover that mountains of text, it's like this. looks like it prints the html and does not render it.

![1631664735](https://user-images.githubusercontent.com/6182099/133350195-12d8343f-7c90-473f-921e-91039f9c75a9.png)

Version 1.10.6

**Comment by pyrochlore** [comment]
Hi @felixsanz, 

For some reason the emoji characters (🚶‍♀️ and🏃‍♀️) in your code block or notes are replaced by html img tags.
That's why there are texts like '<img draggable="false" class="emoji" ......' in the rendered view.

You can copy the emoji [here](https://emojipedia.org/woman-walking/).

**Comment by pyrochlore** [comment]
This is not the first time users met this problem.
So I decide add a function to deal with html img tags.

**Comment by felixsanz** [comment]
> Hi @felixsanz,
> 
> For some reasons, the emoji characters ( and) shown in your code block or notes are replaced by html img tags. (They are not emoji characters) That's why there are texts like '<img draggable="false" class="emoji" ......' in the rendered view.
> 
> Please copy the emoji [here](https://emojipedia.org/woman-walking/) and replace those in your code block by the copied ones.
> 
> By the way, did you install any plugin related to emoji?

Yes i know that the code blocks are replaced by html, but doesn't matter where i copy those emojis, or if i use the two emoji plugins available for obsidian, it's always the same result

**Comment by pyrochlore** [comment]
Hi, 
Please download [this example](https://drive.google.com/file/d/12snIYMX6rPd2Op6OgfQqopBJmHQgwMWI/view?usp=sharing) and check if it works.
Here is what I got
![image](https://user-images.githubusercontent.com/3617615/133418468-9e4c705f-c8ab-4459-876e-c48bf139847e.png)

**Comment by felixsanz** [comment]
Nope, same issue. I'm using Linux in case is related

![1631703878](https://user-images.githubusercontent.com/6182099/133422593-82b2f6fd-1aa2-43d1-9097-9b3d6c6cbfdf.png)

**Comment by pyrochlore** [comment]
Mmm…
Will find a Linux machine and do some tests on it.
Thanks for the report.

**Comment by felixsanz** [comment]
The emojis can be displayed with no problem in obsidian.

![1631704894](https://user-images.githubusercontent.com/6182099/133424456-d371ba84-0065-4888-bf52-17a7480b71d1.png)

The problem is your calendar that renders a `<img>` tag instead of the emoji. Maybe the tag is malformed?

**Comment by pyrochlore** [comment]
Tracker did not create any html img tag.
Maybe the unicode characters are modified at some point before fed into Tracker.

The first thought about this is the YAML parser.
Tracker uses the embeded YAML parser provided by Obsidian API.
Maybe the parser behaves different on Linux.

**Comment by felixsanz** [comment]
> Tracker does not create any html img tag.
> Maybe the unicode characters are modified at some point before fed into Tracker.
> 
> The first thought about this is the YAML parser.
> Tracker uses the embeded YAML parser provided by Obsidian API.
> Maybe the parser behaves different on Linux.
> 
> By the way, could you test this for me?
> Use single quotes to wrap the unicode characters
> like this
> searchTarget: ','

doesn't fix it :(

You're right, it's the YAML parser, check this:

https://github.com/blacksmithgu/obsidian-dataview/issues/118

Even the gear emoji displays wrong

**Comment by felixsanz** [comment]
Commit: https://github.com/blacksmithgu/obsidian-dataview/commit/fc7c8e6d65b8e13ebaad94918f971d17385338bb

**Comment by pyrochlore** [comment]
It's different.
We use the function parseYaml from Obsidian API to get parameters from YAML.
Thus if what we got is an image tag, the only option is to turn it back to a emoji character.

**Comment by felixsanz** [comment]
> The problem is similar but the solution is not related.
> We use the function parseYaml from Obsidian API to get parameters from YAML.
> Thus if what we got are image tags, the only option for us is to turn them back to emoji characters.
> Will do it.

The `alt=""` parameter of the image tag already include the emoji, maybe you should insert just the content of the `alt=""` parameter into the calendar, instead of the whole `<img>` tag? If that's a solution looks pretty easy!

**Comment by pyrochlore** [comment]
> The `alt=""` parameter of the image tag already include the emoji, maybe you should insert just the content of the `alt=""` parameter into the calendar, instead of the whole `<img>` tag?

That was my plan.

**Comment by felixsanz** [comment]
Fixed!

![1631720307](https://user-images.githubusercontent.com/6182099/133464677-aac787f4-0541-448d-bbf0-13eeffd7377c.png)

**Comment by pyrochlore** [comment]
Thanks for the fix.

Since image tags could be placed in any field in YAML, the problem should be treated more generally.
Also, we don't want to leave any image tags to the SVG graph building.

Thus, all image tags with alt will be replaced by the text in alt, otherwise replaced by empty string.
A fix has been committed (3810a63) for this.

**Comment by felixsanz** [comment]
It works on the calendar but you say that the problem affects the whole YAML options and it's not fixed there.

Example:

```
...
line:
    title: Weight Log 🚶
...
```

![1631792755](https://user-images.githubusercontent.com/6182099/133606506-9a6ac478-27b7-420f-96b7-199288dc2b15.png)

**Comment by pyrochlore** [comment]
Will fix it.
Really appreciate your report.

**Comment by felixsanz** [comment]
no problem. if you need test specific options count on me

**Comment by pyrochlore** [comment]
Hi @felixsanz,

Thanks again.
The fix was released with version 1.10.7.
You are still welcome to make pull requests or suggestions.
